eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/btfboy/config-repo.git
          username: 731166941@qq.com
          password: qq731166941
management:
  endpoints:
    web:
      expose: "*"
